# Generated by Django 2.2.7 on 2019-11-15 02:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(null=True, verbose_name='Fecha de Hoy')),
                ('entrada', models.CharField(max_length=100, null=True, verbose_name='Entrada')),
                ('plato', models.CharField(max_length=100, null=True, verbose_name='Plato Principal')),
                ('Postre', models.CharField(max_length=100, null=True, verbose_name='Postre')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run', models.CharField(max_length=12, null=True, verbose_name='Rut')),
                ('empresa', models.CharField(max_length=100, null=True, verbose_name='Nombre Empresa')),
                ('cargo', models.CharField(max_length=100, null=True, verbose_name='Cargo Empresa')),
                ('direccion', models.CharField(max_length=100, null=True, verbose_name='Direccion')),
                ('telefono', models.CharField(max_length=100, null=True, verbose_name='Telefono')),
                ('ciudad', models.CharField(max_length=50, null=True, verbose_name='Ciudad')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
