# Generated by Django 2.2.7 on 2019-11-15 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostal', '0002_auto_20191115_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comedor',
            name='precio',
            field=models.IntegerField(null=True, verbose_name='Precio Menu'),
        ),
        migrations.AlterField(
            model_name='comedor2',
            name='precio',
            field=models.IntegerField(null=True, verbose_name='Precio Plato'),
        ),
    ]
