# Generated by Django 2.2.7 on 2019-11-17 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostal', '0003_auto_20191115_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comedor',
            name='fecha',
            field=models.DateField(null=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='comedor2',
            name='servicio',
            field=models.CharField(max_length=100, null=True, verbose_name='Servicio'),
        ),
    ]
